# Generated by Django 5.2.3 on 2025-07-12 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_supplier_gst_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="sku",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="inventory.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_suppliers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="gst_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
