# Generated by Django 5.2.3 on 2025-07-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0008_alter_inventoryitem_options_alter_inventoryitem_sku_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
