# Generated by Django 5.2.3 on 2025-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_inventoryitem_price_alter_supplier_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(max_length=10),
        ),
    ]
