# Generated by Django 5.2.3 on 2025-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_remove_order_items_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                through="inventory.OrderItem", to="inventory.inventoryitem"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("Female", "Female"), ("Male", "Male"), ("Other", "Other")],
                max_length=10,
            ),
        ),
    ]
