# Generated by Django 5.2.3 on 2025-07-13 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_order_items_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(max_length=10),
        ),
    ]
