# Generated by Django 5.2.3 on 2025-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_remove_order_items_remove_supplier_phone_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_i_name_9b5824_idx",
        ),
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_i_quantit_82f142_idx",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                through="inventory.OrderItem", to="inventory.inventoryitem"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="gst_number",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(max_length=10),
        ),
    ]
